//
//  MinecraftBiomeColorMap+CubiomesDefault.swift
//  CubiomesKit
//
//  Created by Marquis Kurt on 10-07-2025.
//

import CubiomesInternal

extension MinecraftBiomeColorMap {
    static func cubiomesDefault() -> Self {
        var biomeMap = MinecraftBiomeColorMap()

        // NOTE(alicerunsonfedora): It's likely that we can just store this in a file somewhere instead of needing to
        // update this function whenever Cubiomes makes an update.

        biomeMap.set(0x000070, for: ocean)
        biomeMap.set(0x8db360, for: plains)
        biomeMap.set(0xfa9418, for: desert)
        biomeMap.set(0x606060, for: windswept_hills)
        biomeMap.set(0x056621, for: forest)
        biomeMap.set(0x0b6a5f, for: taiga)
        biomeMap.set(0x07f9b2, for: swamp)
        biomeMap.set(0x0000ff, for: river)
        biomeMap.set(0x572526, for: nether_wastes)
        biomeMap.set(0x8080ff, for: the_end)
        biomeMap.set(0x7070d6, for: frozen_ocean)
        biomeMap.set(0xa0a0ff, for: frozen_river)
        biomeMap.set(0xffffff, for: snowy_plains)
        biomeMap.set(0xa0a0a0, for: snowy_mountains)
        biomeMap.set(0xff00ff, for: mushroom_fields)
        biomeMap.set(0xa000ff, for: mushroom_field_shore)
        biomeMap.set(0xfade55, for: beach)
        biomeMap.set(0xd25f12, for: desert_hills)
        biomeMap.set(0x22551c, for: wooded_hills)
        biomeMap.set(0x163933, for: taiga_hills)
        biomeMap.set(0x72789a, for: mountain_edge)
        biomeMap.set(0x507b0a, for: jungle)
        biomeMap.set(0x2c4205, for: jungle_hills)
        biomeMap.set(0x60930f, for: sparse_jungle)
        biomeMap.set(0x000030, for: deep_ocean)
        biomeMap.set(0xa2a284, for: stony_shore)
        biomeMap.set(0xfaf0c0, for: snowy_beach)
        biomeMap.set(0x307444, for: birch_forest)
        biomeMap.set(0x1f5f32, for: birch_forest_hills)
        biomeMap.set(0x40511a, for: dark_forest)
        biomeMap.set(0x31554a, for: snowy_taiga)
        biomeMap.set(0x243f36, for: snowy_taiga_hills)
        biomeMap.set(0x596651, for: old_growth_pine_taiga)
        biomeMap.set(0x454f3e, for: giant_tree_taiga_hills)
        biomeMap.set(0x5b7352, for: windswept_forest)
        biomeMap.set(0xbdb25f, for: savanna)
        biomeMap.set(0xa79d64, for: savanna_plateau)
        biomeMap.set(0xd94515, for: badlands)
        biomeMap.set(0xb09765, for: wooded_badlands)
        biomeMap.set(0xca8c65, for: badlands_plateau)
        biomeMap.set(0x4b4bab, for: small_end_islands)
        biomeMap.set(0xc9c959, for: end_midlands)
        biomeMap.set(0xb5b536, for: end_highlands)
        biomeMap.set(0x7070cc, for: end_barrens)
        biomeMap.set(0x0000ac, for: warm_ocean)
        biomeMap.set(0x000090, for: lukewarm_ocean)
        biomeMap.set(0x202070, for: cold_ocean)
        biomeMap.set(0x000050, for: deep_warm_ocean)
        biomeMap.set(0x000040, for: deep_lukewarm_ocean)
        biomeMap.set(0x202038, for: deep_cold_ocean)
        biomeMap.set(0x404090, for: deep_frozen_ocean)
        biomeMap.set(0x2f560f, for: seasonal_forest)
        biomeMap.set(0x47840e, for: rainforest)
        biomeMap.set(0x789e31, for: shrubland)
        biomeMap.set(0x000000, for: the_void)
        biomeMap.set(0xb5db88, for: sunflower_plains)
        biomeMap.set(0xffbc40, for: desert_lakes)
        biomeMap.set(0x888888, for: windswept_gravelly_hills)
        biomeMap.set(0x2d8e49, for: flower_forest)
        biomeMap.set(0x339287, for: taiga_mountains)
        biomeMap.set(0x2fffda, for: swamp_hills)
        biomeMap.set(0xb4dcdc, for: ice_spikes)
        biomeMap.set(0x78a332, for: modified_jungle)
        biomeMap.set(0x88bb37, for: modified_jungle_edge)
        biomeMap.set(0x589c6c, for: old_growth_birch_forest)
        biomeMap.set(0x47875a, for: tall_birch_hills)
        biomeMap.set(0x687942, for: dark_forest_hills)
        biomeMap.set(0x597d72, for: snowy_taiga_mountains)
        biomeMap.set(0x818e79, for: old_growth_spruce_taiga)
        biomeMap.set(0x6d7766, for: giant_spruce_taiga_hills)
        biomeMap.set(0x839b7a, for: modified_gravelly_mountains)
        biomeMap.set(0xe5da87, for: windswept_savanna)
        biomeMap.set(0xcfc58c, for: shattered_savanna_plateau)
        biomeMap.set(0xff6d3d, for: eroded_badlands)
        biomeMap.set(0xd8bf8d, for: modified_wooded_badlands_plateau)
        biomeMap.set(0xf2b48d, for: modified_badlands_plateau)
        biomeMap.set(0x849500, for: bamboo_jungle)
        biomeMap.set(0x5c6c04, for: bamboo_jungle_hills)
        biomeMap.set(0x4d3a2e, for: soul_sand_valley)
        biomeMap.set(0x981a11, for: crimson_forest)
        biomeMap.set(0x49907b, for: warped_forest)
        biomeMap.set(0x645f63, for: basalt_deltas)
        biomeMap.set(0x4e3012, for: dripstone_caves)
        biomeMap.set(0x283c00, for: lush_caves)
        biomeMap.set(0x60a445, for: meadow)
        biomeMap.set(0x47726c, for: grove)
        biomeMap.set(0xc4c4c4, for: snowy_slopes)
        biomeMap.set(0xdcdcc8, for: jagged_peaks)
        biomeMap.set(0xb0b3ce, for: frozen_peaks)
        biomeMap.set(0x7b8f74, for: stony_peaks)
        biomeMap.set(0x031f29, for: deep_dark)
        biomeMap.set(0x2ccc8e, for: mangrove_swamp)
        biomeMap.set(0xff91c8, for: cherry_grove)
        biomeMap.set(0x696d95, for: pale_garden)

        return biomeMap
    }
}
