# Yoinked from: https://danielsaidi.com/blog/2024/03/10/automatically-publish-docc-to-github-pages-with-github-actions

name: DocC Runner

on:
  push:
    branches: ["root"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
# A single job that builds and deploys the DocC documentation
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - uses: swift-actions/setup-swift@v3
        with:
          swift-version: main-snapshot-2025-10-02
      - name: Install Brew Packages
        run: |
          brew update
          brew install libadwaita libshumate
      - name: Build DocC
        run: |
          swift package --disable-sandbox \
            generate-documentation \
            --enable-experimental-combined-documentation \
            --target CubiomesKit \
            --target CubiomesKitCore \
            --target CubiomesMapKit \
            --output-path "docs" \
            --transform-for-static-hosting \
            --hosting-base-path '.'
          
          echo "<script>window.location.href += \"/documentation/cubiomeskit\"</script>" > docs/index.html;
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
