name: Run Test Suite

on:
  push:
    branches: [ "root" ]
  pull_request:
    branches: [ "root" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15, ubuntu-latest] 

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: swift-actions/setup-swift@v3
      with:
        swift-version: main-snapshot-2025-10-02
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
