name: Run Test Suite

on:
  push:
    branches: [ "root" ]
  pull_request:
    branches: [ "root" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: k-arindam/setup-swift@v6.0.0
      with:
        swift-version: 6.0
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v